### ISSUE TITLE
Implement authentication

### ISSUE THREAD

**Issue by parberge** [codelabsab/timereport#15]
We want to make sure that requests are coming from Slack.

Verify that the token from the request matches the token from slack.

See old code for this here: https://github.com/codelabsab/timereport/blob/ee39a915aa380e8ae9eb4fb4ed6106c2cc400991/timereport/timereport.py#L30

**Comment by kamigerami** [comment]
slack has it's own slack auth token we can verify against. The event that we get has a slack token in it that we can verify against. We did that already in the old version.

https://github.com/codelabsab/timereport/blob/ee39a915aa380e8ae9eb4fb4ed6106c2cc400991/timereport/timereport.py#L30

**Comment by parberge** [comment]
Right. And you don't need the slack client to do that?

**Comment by parberge** [comment]
Just looked at the old code. It's just that I don't know if supplying the token to the lambda and the code and use that to verify is the best practice for security. Maybe it's good enough.

I would prefer that the slash command post would send a token somehow and the API gw would be responsible to verify it.

Just my opinion

**Comment by tommymalmqvist** [comment]
@parberge You get a token with the slack payload which you then compare to the SLACK_TOKEN set in the os.environ via aws vars. If the token is equal it means the client know the secret and the sessions continues.

**Comment by tommymalmqvist** [comment]
The API GW can't do anything but wrap the data sent with some aws meta-data.

From the slack docs I can see the following:


> token | This is a verification token, a deprecated feature that you  shouldn't use any more. It was used to verify that requests were  legitimately being sent by Slack to your app, but you should use the signed secrets functionality to do this instead.

Link to signed secret docs: https://api.slack.com/docs/verifying-requests-from-slack

**Comment by kamigerami** [comment]
exactly like that. That's how they do it everywhere and it's best practice

**Comment by parberge** [comment]
I've read somewhere that having secrets in environment variables is not that good. Also if verification could be done (authorizor for AWS API gw) without triggering the lambda that would be better right? But hey, using the old way is probably good. Just wanted to think about it if it could be better

**Comment by parberge** [comment]
I think I misunderstood the authentication options available for AWS API gw. 

Lets use the slack token 👍
