### ISSUE TITLE
modify frontend to use python-backend

### ISSUE THREAD

**Issue by kamigerami** [codelabsab/timereport#48]
Currently the react frontend uses the node-js backend
let's change that so we can use the python-backend instead

**Comment by parberge** [comment]
Is this really related to timereport-repo?

I think this should be in repo for the frontend?

**Comment by parberge** [comment]
@kamigerami This ticket should be transfered to https://github.com/codelabsab/timereport-react right?

**Comment by kamigerami** [comment]
yes - this should be in the https://github.com/codelabsab/timereport-dummy-ui
