### ISSUE TITLE
Make confirmation window only visable to user

### ISSUE THREAD

**Issue by parberge** [codelabsab/timereport#49]

**Comment by parberge** [comment]
@kamigerami @tommymalmqvist What do you say?
Personally I think this should be done ASAP.
The only bad thing is that it's kind of hard to implement this without deploying to production for testing 😄

**Comment by kamigerami** [comment]
is part of Make feedback messages only visible to users #63

**Comment by parberge** [comment]
FYI @kamigerami @tommymalmqvist : The ephemeral approach didn't work since it doesn't contain the necessary data from the original message.

We will now send the confirmation message as a direct message to the user intead.
