### ISSUE TITLE
Make feedback messages only visible to users

### ISSUE THREAD

**Issue by parberge** [codelabsab/timereport#63]
Kind of related to #49. When we press "Submit" or "no" on confirmation the feedback of the command is visible to the whole channel.

I think it should be to the user only.

![image](https://user-images.githubusercontent.com/5441497/53244431-289a0200-36ab-11e9-89ed-66fb601603ee.png)

**Comment by kamigerami** [comment]
I think we should have all messages and responses only visible to the user

**Comment by parberge** [comment]
@kamigerami I agree. The reason for creating two tickets (this and #49 ) is to minimize the change needed. This ticket will touch the `slack_client_responder` function, and #49 will probably be touching the `slack_responder`.
