### ISSUE TITLE
Map slack user_name to user_id and preferable e-mail

### ISSUE THREAD

**Issue by kamigerami** [codelabsab/timereport#66]
If we are to present data in a frontend we need to know the user-names of everybody and map the user-id to the user-name if we are to search the backend with /users/<user_id> but selecting a "name" in the frontend UI

**Comment by parberge** [comment]
@kamigerami Every event that timereport generates, doesn't it already contain the username?

**Comment by kamigerami** [comment]
This has already been implemented in backend : https://github.com/codelabsab/timereport_backend/commit/8e4092e9e023523b7e2263baa1e5050ff37b2edc
