### ISSUE TITLE
Change directory layout to make import with chalice better

### ISSUE THREAD

**Issue by parberge** [codelabsab/timereport#77]
So one main problem we have with imports the way chalice wants it is that our editors and IDE's complain about it.

And even though this seem trivial, it hinders our development capabilities when the editor can't help us.

Is there a way to create a directory layout that works for both chalice and our IDE's?

**Comment by parberge** [comment]
I created a new branch where atleast the unit test works 😏 
https://github.com/codelabsab/timereport/tree/fix_dir_layout

**Comment by parberge** [comment]
To get `chalice local` to work you need to manually setup the `.chalice` directory.

I did:
`git checkout master -- timereport/.chalice`
`mv timereport/.chalice .`

**Comment by parberge** [comment]
@kamigerami @tommymalmqvist Thoughts?

**Comment by kamigerami** [comment]
hmmm not sure .. we should test it? .chalice should be in root if that is the case

**Comment by parberge** [comment]
@kamigerami Verified to work with `chalice local` when I move `.chalice` desrcibed above.

Would be good to do some actual testing, like deploy it to dev or something.

**Comment by parberge** [comment]
Fixed in #79
