### ISSUE TITLE
create end to end deployment pipeline for testing

### ISSUE THREAD

**Issue by kamigerami** [codelabsab/timereport#8]
1. on push to repo trigger hook to:
2. get source code
3. codebuild: cloudformation pipeline
4. setup dynamodb database
5. insert passwords into ssm
4. codedeploy: chalice deploy with ssm passwords as env variables
5. run test suite
6. OK? 
7. deploy to prod stage
8. tear down (or keep pipeline and update lambda code only)

**Comment by parberge** [comment]
@kamigerami We don't use codebuild or codedeploy as of now.
Also not chalice :)

Can you update this to make it more clear on the high level detail of how the pipeline will work

**Comment by kamigerami** [comment]
closing this in favour of .travis and chalice
